// lib/airport-codes.ts
// Comprehensive Airport IATA code to full name lookup table with cities/countries

export const AIRPORT_CODES: { [key: string]: string } = {
  // MAJOR EUROPEAN DESTINATIONS FROM SCHIPHOL
  'LHR': 'London Heathrow Airport, United Kingdom',
  'LGW': 'London Gatwick Airport, United Kingdom',
  'STN': 'London Stansted Airport, United Kingdom',
  'LTN': 'London Luton Airport, United Kingdom',
  'LCY': 'London City Airport, United Kingdom',
  'CDG': 'Paris Charles de Gaulle Airport, France',
  'ORY': 'Paris Orly Airport, France',
  'FRA': 'Frankfurt Airport, Germany',
  'MUC': 'Munich Airport, Germany',
  'DUS': 'Düsseldorf Airport, Germany',
  'HAM': 'Hamburg Airport, Germany',
  'STR': 'Stuttgart Airport, Germany',
  'CGN': 'Cologne Bonn Airport, Germany',
  'BRE': 'Bremen Airport, Germany',
  'NUE': 'Nuremberg Airport, Germany',
  'LEJ': 'Leipzig/Halle Airport, Germany',
  'DRS': 'Dresden Airport, Germany',
  'BCN': 'Barcelona Airport, Spain',
  'MAD': 'Madrid-Barajas Airport, Spain',
  'PMI': 'Palma de Mallorca Airport, Spain',
  'IBZ': 'Ibiza Airport, Spain',
  'MAH': 'Menorca Airport, Spain',
  'AGP': 'Málaga Airport, Spain',
  'ALC': 'Alicante Airport, Spain',
  'VLC': 'Valencia Airport, Spain',
  'SVQ': 'Seville Airport, Spain',
  'BIO': 'Bilbao Airport, Spain',
  'SDR': 'Santander Airport, Spain',
  'LCG': 'A Coruña Airport, Spain',
  'FCO': 'Rome Fiumicino Airport, Italy',
  'CIA': 'Rome Ciampino Airport, Italy',
  'MXP': 'Milan Malpensa Airport, Italy',
  'BGY': 'Milan Bergamo Airport, Italy',
  'LIN': 'Milan Linate Airport, Italy',
  'VCE': 'Venice Marco Polo Airport, Italy',
  'TSF': 'Venice Treviso Airport, Italy',
  'BLQ': 'Bologna Airport, Italy',
  'FLR': 'Florence Airport, Italy',
  'PSA': 'Pisa Airport, Italy',
  'NAP': 'Naples Airport, Italy',
  'CTA': 'Catania Airport, Italy',
  'PMO': 'Palermo Airport, Italy',
  'CAG': 'Cagliari Airport, Italy',
  'ZUR': 'Zurich Airport, Switzerland',
  'GVA': 'Geneva Airport, Switzerland',
  'BSL': 'Basel Airport, Switzerland',
  'BRN': 'Bern Airport, Switzerland',
  'VIE': 'Vienna International Airport, Austria',
  'SZG': 'Salzburg Airport, Austria',
  'INN': 'Innsbruck Airport, Austria',
  'GRZ': 'Graz Airport, Austria',
  'CPH': 'Copenhagen Airport, Denmark',
  'AAL': 'Aalborg Airport, Denmark',
  'AAR': 'Aarhus Airport, Denmark',
  'BLL': 'Billund Airport, Denmark',
  'ARN': 'Stockholm Arlanda Airport, Sweden',
  'BMA': 'Stockholm Bromma Airport, Sweden',
  'NYO': 'Stockholm Skavsta Airport, Sweden',
  'GOT': 'Gothenburg Airport, Sweden',
  'MMX': 'Malmö Airport, Sweden',
  'UME': 'Umeå Airport, Sweden',
  'LLA': 'Luleå Airport, Sweden',
  'OSL': 'Oslo Airport, Norway',
  'BGO': 'Bergen Airport, Norway',
  'TRD': 'Trondheim Airport, Norway',
  'SVG': 'Stavanger Airport, Norway',
  'KRS': 'Kristiansand Airport, Norway',
  'MOL': 'Molde Airport, Norway',
  'BRU': 'Brussels Airport, Belgium',
  'CRL': 'Brussels Charleroi Airport, Belgium',
  'ANR': 'Antwerp Airport, Belgium',
  'LIS': 'Lisbon Airport, Portugal',
  'OPO': 'Porto Airport, Portugal',
  'FAO': 'Faro Airport, Portugal',
  'FNC': 'Funchal Airport, Madeira, Portugal',
  'PDL': 'Ponta Delgada Airport, Azores, Portugal',
  'PRG': 'Prague Airport, Czech Republic',
  'BRQ': 'Brno Airport, Czech Republic',
  'OSR': 'Ostrava Airport, Czech Republic',
  'WAW': 'Warsaw Chopin Airport, Poland',
  'KRK': 'Krakow Airport, Poland',
  'GDN': 'Gdansk Airport, Poland',
  'WRO': 'Wrocław Airport, Poland',
  'POZ': 'Poznań Airport, Poland',
  'KTW': 'Katowice Airport, Poland',
  'ATH': 'Athens International Airport, Greece',
  'SKG': 'Thessaloniki Airport, Greece',
  'HER': 'Heraklion Airport, Crete, Greece',
  'CHQ': 'Chania Airport, Crete, Greece',
  'RHO': 'Rhodes Airport, Greece',
  'KOS': 'Kos Airport, Greece',
  'JTR': 'Santorini Airport, Greece',
  'MYK': 'Mykonos Airport, Greece',
  'CFU': 'Corfu Airport, Greece',
  'ZTH': 'Zakynthos Airport, Greece',
  'IST': 'Istanbul Airport, Turkey',
  'SAW': 'Istanbul Sabiha Gökçen Airport, Turkey',
  'AYT': 'Antalya Airport, Turkey',
  'ESB': 'Ankara Airport, Turkey',
  'ADB': 'Izmir Airport, Turkey',
  'BJV': 'Bodrum Airport, Turkey',
  'DLM': 'Dalaman Airport, Turkey',
  'HEL': 'Helsinki Airport, Finland',
  'TMP': 'Tampere Airport, Finland',
  'TKU': 'Turku Airport, Finland',
  'OUL': 'Oulu Airport, Finland',
  'RVN': 'Rovaniemi Airport, Finland',
  'RIX': 'Riga Airport, Latvia',
  'TLL': 'Tallinn Airport, Estonia',
  'VNO': 'Vilnius Airport, Lithuania',
  'KUN': 'Kaunas Airport, Lithuania',
  'DUB': 'Dublin Airport, Ireland',
  'ORK': 'Cork Airport, Ireland',
  'SNN': 'Shannon Airport, Ireland',
  'KIR': 'Kerry Airport, Ireland',
  'NOC': 'Ireland West Airport, Ireland',
  'EDI': 'Edinburgh Airport, Scotland',
  'GLA': 'Glasgow Airport, Scotland',
  'PIK': 'Glasgow Prestwick Airport, Scotland',
  'ABZ': 'Aberdeen Airport, Scotland',
  'INV': 'Inverness Airport, Scotland',
  'SYY': 'Stornoway Airport, Scotland',
  'MAN': 'Manchester Airport, United Kingdom',
  'BHX': 'Birmingham Airport, United Kingdom',
  'LBA': 'Leeds Bradford Airport, United Kingdom',
  'NCL': 'Newcastle Airport, United Kingdom',
  'MME': 'Durham Tees Valley Airport, United Kingdom',
  'CWL': 'Cardiff Airport, Wales',
  'BRS': 'Bristol Airport, United Kingdom',
  'EXT': 'Exeter Airport, United Kingdom',
  'NWI': 'Norwich Airport, United Kingdom',
  'EMA': 'East Midlands Airport, United Kingdom',
  'BEL': 'Belgrade Airport, Serbia',
  'ZAG': 'Zagreb Airport, Croatia',
  'SPU': 'Split Airport, Croatia',
  'DBV': 'Dubrovnik Airport, Croatia',
  'PUY': 'Pula Airport, Croatia',
  'RJK': 'Rijeka Airport, Croatia',
  'LJU': 'Ljubljana Airport, Slovenia',
  'MBX': 'Maribor Airport, Slovenia',
  'SJJ': 'Sarajevo Airport, Bosnia and Herzegovina',
  'TZL': 'Tuzla Airport, Bosnia and Herzegovina',
  'SKP': 'Skopje Airport, North Macedonia',
  'OHD': 'Ohrid Airport, North Macedonia',
  'TIA': 'Tirana Airport, Albania',
  'PRN': 'Pristina Airport, Kosovo',
  'PDG': 'Podgorica Airport, Montenegro',
  'TIV': 'Tivat Airport, Montenegro',
  'BUD': 'Budapest Airport, Hungary',
  'DEB': 'Debrecen Airport, Hungary',
  'OTP': 'Bucharest Henri Coandă Airport, Romania',
  'BBU': 'Bucharest Băneasa Airport, Romania',
  'CLJ': 'Cluj-Napoca Airport, Romania',
  'TSR': 'Timișoara Airport, Romania',
  'IAS': 'Iași Airport, Romania',
  'CND': 'Constanța Airport, Romania',
  'SOF': 'Sofia Airport, Bulgaria',
  'PDV': 'Plovdiv Airport, Bulgaria',
  'VAR': 'Varna Airport, Bulgaria',
  'BOJ': 'Burgas Airport, Bulgaria',

  // NORTH AMERICA
  'JFK': 'John F. Kennedy International Airport, New York, USA',
  'LGA': 'LaGuardia Airport, New York, USA',
  'EWR': 'Newark Liberty International Airport, New Jersey, USA',
  'BOS': 'Boston Logan International Airport, Massachusetts, USA',
  'DCA': 'Ronald Reagan Washington National Airport, Washington DC, USA',
  'IAD': 'Washington Dulles International Airport, Virginia, USA',
  'BWI': 'Baltimore/Washington International Airport, Maryland, USA',
  'PHL': 'Philadelphia International Airport, Pennsylvania, USA',
  'CLT': 'Charlotte Douglas International Airport, North Carolina, USA',
  'RDU': 'Raleigh-Durham International Airport, North Carolina, USA',
  'ATL': 'Hartsfield-Jackson Atlanta International Airport, Georgia, USA',
  'MIA': 'Miami International Airport, Florida, USA',
  'FLL': 'Fort Lauderdale-Hollywood International Airport, Florida, USA',
  'PBI': 'Palm Beach International Airport, Florida, USA',
  'TPA': 'Tampa International Airport, Florida, USA',
  'MCO': 'Orlando International Airport, Florida, USA',
  'JAX': 'Jacksonville International Airport, Florida, USA',
  'MSY': 'Louis Armstrong New Orleans International Airport, Louisiana, USA',
  'IAH': 'George Bush Intercontinental Airport, Houston, Texas, USA',
  'DFW': 'Dallas/Fort Worth International Airport, Texas, USA',
  'DAL': 'Dallas Love Field, Texas, USA',
  'AUS': 'Austin-Bergstrom International Airport, Texas, USA',
  'SAT': 'San Antonio International Airport, Texas, USA',
  'MSP': 'Minneapolis-Saint Paul International Airport, Minnesota, USA',
  'ORD': 'Chicago O\'Hare International Airport, Illinois, USA',
  'MDW': 'Chicago Midway International Airport, Illinois, USA',
  'MKE': 'Milwaukee Mitchell International Airport, Wisconsin, USA',
  'DTW': 'Detroit Metropolitan Airport, Michigan, USA',
  'CLE': 'Cleveland Hopkins International Airport, Ohio, USA',
  'CVG': 'Cincinnati/Northern Kentucky International Airport, Kentucky, USA',
  'CMH': 'John Glenn Columbus International Airport, Ohio, USA',
  'IND': 'Indianapolis International Airport, Indiana, USA',
  'MCI': 'Kansas City International Airport, Missouri, USA',
  'STL': 'Lambert-St. Louis International Airport, Missouri, USA',
  'DEN': 'Denver International Airport, Colorado, USA',
  'PHX': 'Phoenix Sky Harbor International Airport, Arizona, USA',
  'TUS': 'Tucson International Airport, Arizona, USA',
  'LAS': 'Harry Reid International Airport, Las Vegas, Nevada, USA',
  'RNO': 'Reno-Tahoe International Airport, Nevada, USA',
  'LAX': 'Los Angeles International Airport, California, USA',
  'BUR': 'Hollywood Burbank Airport, California, USA',
  'LGB': 'Long Beach Airport, California, USA',
  'ONT': 'Ontario International Airport, California, USA',
  'SNA': 'John Wayne Airport, Orange County, California, USA',
  'PSP': 'Palm Springs International Airport, California, USA',
  'SAN': 'San Diego International Airport, California, USA',
  'SFO': 'San Francisco International Airport, California, USA',
  'OAK': 'Oakland International Airport, California, USA',
  'SJC': 'Norman Y. Mineta San José International Airport, California, USA',
  'SMF': 'Sacramento International Airport, California, USA',
  'FAT': 'Fresno Yosemite International Airport, California, USA',
  'SEA': 'Seattle-Tacoma International Airport, Washington, USA',
  'BFI': 'Boeing Field, Seattle, Washington, USA',
  'GEG': 'Spokane International Airport, Washington, USA',
  'PDX': 'Portland International Airport, Oregon, USA',
  'EUG': 'Eugene Airport, Oregon, USA',
  'BOI': 'Boise Airport, Idaho, USA',
  'SLC': 'Salt Lake City International Airport, Utah, USA',
  'BZN': 'Bozeman Yellowstone International Airport, Montana, USA',
  'BIL': 'Billings Logan International Airport, Montana, USA',
  'FCA': 'Glacier Park International Airport, Montana, USA',
  'ANC': 'Ted Stevens Anchorage International Airport, Alaska, USA',
  'FAI': 'Fairbanks International Airport, Alaska, USA',
  'JNU': 'Juneau International Airport, Alaska, USA',
  'HNL': 'Daniel K. Inouye International Airport, Honolulu, Hawaii, USA',
  'OGG': 'Kahului Airport, Maui, Hawaii, USA',
  'KOA': 'Ellison Onizuka Kona International Airport, Hawaii, USA',
  'LIH': 'Lihue Airport, Kauai, Hawaii, USA',
  'ITO': 'Hilo International Airport, Hawaii, USA',

  // CANADA
  'YYZ': 'Toronto Pearson International Airport, Ontario, Canada',
  'YTZ': 'Billy Bishop Toronto City Airport, Ontario, Canada',
  'YHM': 'John C. Munro Hamilton International Airport, Ontario, Canada',
  'YOW': 'Ottawa Macdonald-Cartier International Airport, Ontario, Canada',
  'YUL': 'Montreal-Pierre Elliott Trudeau International Airport, Quebec, Canada',
  'YMX': 'Montreal-Mirabel International Airport, Quebec, Canada',
  'YQB': 'Quebec City Jean Lesage International Airport, Quebec, Canada',
  'YHZ': 'Halifax Stanfield International Airport, Nova Scotia, Canada',
  'YYT': 'St. John\'s International Airport, Newfoundland, Canada',
  'YDF': 'Deer Lake Regional Airport, Newfoundland, Canada',
  'YQX': 'Gander International Airport, Newfoundland, Canada',
  'YVR': 'Vancouver International Airport, British Columbia, Canada',
  'YKA': 'Kamloops Airport, British Columbia, Canada',
  'YKF': 'Kitchener/Waterloo Airport, Ontario, Canada',
  'YYC': 'Calgary International Airport, Alberta, Canada',
  'YEG': 'Edmonton International Airport, Alberta, Canada',
  'YXE': 'Saskatoon John G. Diefenbaker International Airport, Saskatchewan, Canada',
  'YQR': 'Regina Airport, Saskatchewan, Canada',
  'YWG': 'Winnipeg James Armstrong Richardson International Airport, Manitoba, Canada',
  'YFB': 'Iqaluit Airport, Nunavut, Canada',
  'YZF': 'Yellowknife Airport, Northwest Territories, Canada',
  'YXY': 'Whitehorse Airport, Yukon, Canada',

  // CENTRAL & SOUTH AMERICA
  'MEX': 'Mexico City International Airport, Mexico',
  'CUN': 'Cancún International Airport, Mexico',
  'GDL': 'Guadalajara Airport, Mexico',
  'PVR': 'Puerto Vallarta Airport, Mexico',
  'CZM': 'Cozumel International Airport, Mexico',
  'MZT': 'Mazatlán Airport, Mexico',
  'ACA': 'Acapulco Airport, Mexico',
  'HUX': 'Huatulco Airport, Mexico',
  'OAX': 'Oaxaca Airport, Mexico',
  'VSA': 'Villahermosa Airport, Mexico',
  'CJS': 'Ciudad Juárez Airport, Mexico',
  'TIJ': 'Tijuana Airport, Mexico',
  'LAP': 'La Paz Airport, Mexico',
  'SJD': 'Los Cabos International Airport, Mexico',
  'GTM': 'Guatemala City Airport, Guatemala',
  'BZE': 'Philip S. W. Goldson International Airport, Belize',
  'SAL': 'El Salvador International Airport, El Salvador',
  'TGU': 'Tegucigalpa Airport, Honduras',
  'SAP': 'San Pedro Sula Airport, Honduras',
  'MGA': 'Managua Airport, Nicaragua',
  'LIR': 'Liberia Airport, Costa Rica',
  'SJO': 'Juan Santamaría International Airport, San José, Costa Rica',
  'PTY': 'Tocumen International Airport, Panama City, Panama',
  'BOG': 'El Dorado International Airport, Bogotá, Colombia',
  'CTG': 'Rafael Núñez International Airport, Cartagena, Colombia',
  'MDE': 'José María Córdova Airfield, Medellín, Colombia',
  'CLO': 'Alfonso Bonilla Aragón International Airport, Cali, Colombia',
  'CCS': 'Simón Bolívar International Airport, Caracas, Venezuela',
  'GEO': 'Cheddi Jagan International Airport, Georgetown, Guyana',
  'PBM': 'Johan Adolf Pengel International Airport, Paramaribo, Suriname',
  'CAY': 'Rochambeau Airport, Cayenne, French Guiana',
  'GRU': 'São Paulo/Guarulhos International Airport, Brazil',
  'GIG': 'Rio de Janeiro/Galeão International Airport, Brazil',
  'SDU': 'Santos Dumont Airport, Rio de Janeiro, Brazil',
  'CGH': 'Congonhas Airport, São Paulo, Brazil',
  'BSB': 'Brasília International Airport, Brazil',
  'CNF': 'Belo Horizonte/Confins International Airport, Brazil',
  'PLU': 'Belo Horizonte/Pampulha Airport, Brazil',
  'REC': 'Recife/Guararapes International Airport, Brazil',
  'FOR': 'Fortaleza International Airport, Brazil',
  'SSA': 'Salvador Airport, Brazil',
  'MAO': 'Eduardo Gomes International Airport, Manaus, Brazil',
  'CWB': 'Afonso Pena International Airport, Curitiba, Brazil',
  'POA': 'Salgado Filho International Airport, Porto Alegre, Brazil',
  'FLN': 'Hercílio Luz International Airport, Florianópolis, Brazil',
  'VIX': 'Eurico de Aguiar Salles Airport, Vitória, Brazil',
  'EZE': 'Ezeiza International Airport, Buenos Aires, Argentina',
  'AEP': 'Jorge Newbery Airfield, Buenos Aires, Argentina',
  'COR': 'Córdoba Airport, Argentina',
  'MDZ': 'Governor Francisco Gabrielli Airfield, Mendoza, Argentina',
  'BRC': 'San Carlos de Bariloche Airport, Argentina',
  'IGR': 'Cataratas del Iguazú International Airport, Argentina',
  'SCL': 'Santiago International Airport, Chile',
  'LSC': 'La Serena Airport, Chile',
  'CJC': 'Calama Airport, Chile',
  'IQQ': 'Diego Aracena International Airport, Iquique, Chile',
  'ANF': 'Antofagasta Airport, Chile',
  'CPO': 'Chamonate Airport, Copiapó, Chile',
  'PMC': 'El Tepual Airport, Puerto Montt, Chile',
  'PUQ': 'Presidente Carlos Ibáñez del Campo International Airport, Punta Arenas, Chile',
  'LIM': 'Jorge Chávez International Airport, Lima, Peru',
  'CUZ': 'Alejandro Velasco Astete International Airport, Cusco, Peru',
  'AQP': 'Alfredo Rodríguez Ballón International Airport, Arequipa, Peru',
  'TRU': 'Capitán FAP Carlos Martínez de Pinillos International Airport, Trujillo, Peru',
  'PIU': 'Capitán FAP Guillermo Concha Iberico International Airport, Piura, Peru',
  'UIO': 'Mariscal Sucre International Airport, Quito, Ecuador',
  'GYE': 'José Joaquín de Olmedo International Airport, Guayaquil, Ecuador',
  'GPS': 'Seymour Airport, Galápagos, Ecuador',
  'LPB': 'El Alto International Airport, La Paz, Bolivia',
  'CBB': 'Jorge Wilstermann Airfield, Cochabamba, Bolivia',
  'SRE': 'Juana Azurduy de Padilla International Airport, Sucre, Bolivia',
  'SRZ': 'El Trompillo Airport, Santa Cruz, Bolivia',
  'ASU': 'Silvio Pettirossi International Airport, Asunción, Paraguay',
  'CDE': 'Ciudad del Este Airport, Paraguay',
  'MVD': 'Montevideo Airport, Uruguay',
  'PDP': 'Capitán de Corbeta Carlos A. Curbelo International Airport, Punta del Este, Uruguay',

  // CARIBBEAN
  'CUR': 'Hato International Airport, Curaçao',
  'AUA': 'Queen Beatrix International Airport, Aruba',
  'BON': 'Flamingo International Airport, Bonaire',
  'SXM': 'Princess Juliana International Airport, Sint Maarten',
  'AXA': 'Clayton J. Lloyd International Airport, Anguilla',
  'BGI': 'Grantley Adams International Airport, Barbados',
  'POS': 'Piarco International Airport, Port of Spain, Trinidad',
  'GND': 'Maurice Bishop International Airport, St. George\'s, Grenada',
  'SVD': 'Argyle International Airport, St. Vincent and the Grenadines',
  'UVF': 'Hewanorra International Airport, St. Lucia',
  'SLU': 'George F. L. Charles Airport, St. Lucia',
  'DOM': 'Douglas-Charles Airport, Dominica',
  'ANU': 'V.C. Bird International Airport, St. John\'s, Antigua',
  'SKB': 'Robert L. Bradshaw International Airport, St. Kitts',
  'NEV': 'Vance W. Amory International Airport, Nevis',
  'EIS': 'Terrance B. Lettsome International Airport, Tortola, British Virgin Islands',
  'STT': 'Cyril E. King Airport, St. Thomas, US Virgin Islands',
  'STX': 'Henry E. Rohlsen Airport, St. Croix, US Virgin Islands',
  'SJU': 'Luis Muñoz Marín International Airport, San Juan, Puerto Rico',
  'PSE': 'Mercedita Airport, Ponce, Puerto Rico',
  'BQN': 'Rafael Hernández Airport, Aguadilla, Puerto Rico',
  'SDQ': 'Las Américas International Airport, Santo Domingo, Dominican Republic',
  'PUJ': 'Punta Cana International Airport, Dominican Republic',
  'STI': 'Cibao International Airport, Santiago, Dominican Republic',
  'PAP': 'Toussaint Louverture International Airport, Port-au-Prince, Haiti',
  'CAP': 'Cap-Haïtien International Airport, Haiti',
  'KIN': 'Norman Manley International Airport, Kingston, Jamaica',
  'MBJ': 'Sangster International Airport, Montego Bay, Jamaica',
  'OCJ': 'Boscobel Airport, Ocho Rios, Jamaica',
  'HAV': 'José Martí International Airport, Havana, Cuba',
  'VRA': 'Juan Gualberto Gómez Airport, Varadero, Cuba',
  'SCU': 'Antonio Maceo Airport, Santiago de Cuba, Cuba',
  'HOG': 'Frank País Airport, Holguín, Cuba',
  'CCC': 'Cayo Coco Airport, Cuba',
  'NAS': 'Lynden Pindling International Airport, Nassau, Bahamas',
  'FPO': 'Grand Bahama International Airport, Freeport, Bahamas',
  'GGT': 'Exuma International Airport, Bahamas',
  'ELH': 'North Eleuthera Airport, Bahamas',
  'RSD': 'Rock Sound Airport, Bahamas',

  // ASIA PACIFIC
  'SIN': 'Singapore Changi Airport, Singapore',
  'NRT': 'Tokyo Narita International Airport, Japan',
  'HND': 'Tokyo Haneda Airport, Japan',
  'KIX': 'Kansai International Airport, Osaka, Japan',
  'ITM': 'Osaka International Airport, Japan',
  'NGO': 'Chubu Centrair International Airport, Nagoya, Japan',
  'FUK': 'Fukuoka Airport, Japan',
  'CTS': 'New Chitose Airport, Sapporo, Japan',
  'SDJ': 'Sendai Airport, Japan',
  'HIJ': 'Hiroshima Airport, Japan',
  'TAK': 'Takamatsu Airport, Japan',
  'KMJ': 'Kumamoto Airport, Japan',
  'KOJ': 'Kagoshima Airport, Japan',
  'OKA': 'Naha Airport, Okinawa, Japan',
  'ICN': 'Seoul Incheon International Airport, South Korea',
  'GMP': 'Seoul Gimpo International Airport, South Korea',
  'PUS': 'Busan Airport, South Korea',
  'CJU': 'Jeju International Airport, South Korea',
  'TAE': 'Daegu International Airport, South Korea',
  'RSU': 'Yeosu Airport, South Korea',
  'HKG': 'Hong Kong International Airport, Hong Kong',
  'MFM': 'Macau International Airport, Macau',
  'TPE': 'Taiwan Taoyuan International Airport, Taiwan',
  'TSA': 'Taipei Songshan Airport, Taiwan',
  'KHH': 'Kaohsiung International Airport, Taiwan',
  'RMQ': 'Taichung Airport, Taiwan',
  'MZG': 'Magong Airport, Penghu, Taiwan',
  'PEK': 'Beijing Capital International Airport, China',
  'PKX': 'Beijing Daxing International Airport, China',
  'PVG': 'Shanghai Pudong International Airport, China',
  'SHA': 'Shanghai Hongqiao International Airport, China',
  'CAN': 'Guangzhou Baiyun International Airport, China',
  'SZX': 'Shenzhen Bao\'an International Airport, China',
  'CTU': 'Chengdu Shuangliu International Airport, China',
  'TFU': 'Chengdu Tianfu International Airport, China',
  'KMG': 'Kunming Changshui International Airport, China',
  'XIY': 'Xi\'an Xianyang International Airport, China',
  'WUH': 'Wuhan Tianhe International Airport, China',
  'CSX': 'Changsha Huanghua International Airport, China',
  'NKG': 'Nanjing Lukou International Airport, China',
  'HGH': 'Hangzhou Xiaoshan International Airport, China',
  'FOC': 'Fuzhou Changle International Airport, China',
  'XMN': 'Xiamen Gaoqi International Airport, China',
  'DLC': 'Dalian Zhoushuizi International Airport, China',
  'SHE': 'Shenyang Taoxian International Airport, China',
  'HRB': 'Harbin Taiping International Airport, China',
  'TSN': 'Tianjin Binhai International Airport, China',
  'TNA': 'Jinan Yaoqiang International Airport, China',
  'TAO': 'Qingdao Jiaodong International Airport, China',
  'URC': 'Ürümqi Diwopu International Airport, China',
  'LHW': 'Lanzhou Zhongchuan Airport, China',
  'INC': 'Yinchuan Hedong Airport, China',
  'BKK': 'Bangkok Suvarnabhumi Airport, Thailand',
  'DMK': 'Bangkok Don Mueang International Airport, Thailand',
  'CNX': 'Chiang Mai International Airport, Thailand',
  'HKT': 'Phuket International Airport, Thailand',
  'USM': 'Ko Samui Airport, Thailand',
  'UTP': 'U-Tapao International Airport, Thailand',
  'HDY': 'Hat Yai International Airport, Thailand',
  'UNN': 'Ranong Airport, Thailand',
  'TDX': 'Trat Airport, Thailand',
  'ROI': 'Roi Et Airport, Thailand',
  'KUL': 'Kuala Lumpur International Airport, Malaysia',
  'SZB': 'Sultan Abdul Aziz Shah Airport, Kuala Lumpur, Malaysia',
  'JHB': 'Senai International Airport, Johor Bahru, Malaysia',
  'KCH': 'Kuching International Airport, Malaysia',
  'BKI': 'Kota Kinabalu International Airport, Malaysia',
  'MYY': 'Miri Airport, Malaysia',
  'SDK': 'Sandakan Airport, Malaysia',
  'LBU': 'Labuan Airport, Malaysia',
  'PEN': 'Penang International Airport, Malaysia',
  'LGK': 'Langkawi International Airport, Malaysia',
  'IPH': 'Sultan Azlan Shah Airport, Ipoh, Malaysia',
  'TGG': 'Sultan Mahmud Airport, Kuala Terengganu, Malaysia',
  'CGK': 'Soekarno-Hatta International Airport, Jakarta, Indonesia',
  'HLP': 'Halim Perdanakusuma International Airport, Jakarta, Indonesia',
  'DPS': 'Ngurah Rai International Airport, Bali, Indonesia',
  'MLG': 'Abdul Rachman Saleh Airport, Malang, Indonesia',
  'JOG': 'Yogyakarta International Airport, Indonesia',
  'SRG': 'Achmad Yani Airport, Semarang, Indonesia',
  'SLO': 'Adisutcipto Airport, Solo, Indonesia',
  'MDC': 'Sam Ratulangi Airport, Manado, Indonesia',
  'MKW': 'Rendani Airport, Manokwari, Indonesia',
  'BPN': 'Sultan Aji Muhammad Sulaiman Airport, Balikpapan, Indonesia',
  'PLM': 'Sultan Mahmud Badaruddin II Airport, Palembang, Indonesia',
  'PKU': 'Sultan Syarif Kasim II Airport, Pekanbaru, Indonesia',
  'PDG_ID': 'Minangkabau International Airport, Padang, Indonesia',
  'BTH': 'Hang Nadim Airport, Batam, Indonesia',
  'TKG': 'Radin Inten II Airport, Bandar Lampung, Indonesia',
  'BJM': 'Syamsudin Noor Airport, Banjarmasin, Indonesia',
  'PNK': 'Supadio Airport, Pontianak, Indonesia',
  'AMI': 'Selaparang Airport, Mataram, Indonesia',
  'LOP': 'Lombok International Airport, Indonesia',
  'UPG': 'Sultan Hasanuddin Airport, Makassar, Indonesia',
  'MNL': 'Ninoy Aquino International Airport, Manila, Philippines',
  'CRK': 'Clark International Airport, Philippines',
  'CEB': 'Mactan-Cebu International Airport, Philippines',
  'DVO': 'Francisco Bangoy International Airport, Davao, Philippines',
  'ILO': 'Iloilo International Airport, Philippines',
  'BCD': 'Bacolod-Silay Airport, Philippines',
  'TAG': 'Tagbilaran Airport, Bohol, Philippines',
  'MPH': 'Godofredo P. Ramos Airport, Caticlan, Philippines',
  'KLO': 'Kalibo International Airport, Philippines',
  'PPS': 'Puerto Princesa Airport, Philippines',
  'ZAM': 'Zamboanga International Airport, Philippines',
  'CGY': 'Laguindingan Airport, Cagayan de Oro, Philippines',
  'GES': 'General Santos Airport, Philippines',
  'SGN': 'Tan Son Nhat International Airport, Ho Chi Minh City, Vietnam',
  'HAN': 'Noi Bai International Airport, Hanoi, Vietnam',
  'DAD': 'Da Nang International Airport, Vietnam',
  'HUI': 'Phu Bai International Airport, Hue, Vietnam',
  'NHA': 'Cam Ranh International Airport, Nha Trang, Vietnam',
  'DLI': 'Lien Khuong Airport, Da Lat, Vietnam',
  'PQC': 'Phu Quoc International Airport, Vietnam',
  'VCA': 'Can Tho International Airport, Vietnam',
  'RGN': 'Yangon International Airport, Myanmar',
  'MDL': 'Mandalay International Airport, Myanmar',
  'NYU': 'Naypyidaw Airport, Myanmar',
  'KTM': 'Tribhuvan International Airport, Kathmandu, Nepal',
  'PKR': 'Pokhara Airport, Nepal',
  'BWA': 'Bhairawa Airport, Nepal',
  'LPQ': 'Luang Prabang Airport, Laos',
  'VTE': 'Wattay International Airport, Vientiane, Laos',
  'PKZ': 'Pakse International Airport, Laos',
  'REP': 'Siem Reap International Airport, Cambodia',
  'PNH': 'Phnom Penh International Airport, Cambodia',
  'KOS_KH': 'Sihanoukville International Airport, Cambodia',

  // SOUTH ASIA
  'BOM': 'Chhatrapati Shivaji Maharaj International Airport, Mumbai, India',
  'DEL': 'Indira Gandhi International Airport, Delhi, India',
  'BLR': 'Kempegowda International Airport, Bangalore, India',
  'MAA': 'Chennai International Airport, India',
  'HYD': 'Rajiv Gandhi International Airport, Hyderabad, India',
  'CCU': 'Netaji Subhash Chandra Bose International Airport, Kolkata, India',
  'AMD': 'Sardar Vallabhbhai Patel International Airport, Ahmedabad, India',
  'PNQ': 'Pune Airport, India',
  'COK': 'Cochin International Airport, Kochi, India',
  'TRV': 'Trivandrum International Airport, India',
  'CJB': 'Coimbatore International Airport, India',
  'MDU': 'Madurai Airport, India',
  'TRZ': 'Tiruchirapalli International Airport, India',
  'SXR': 'Sheikh ul-Alam International Airport, Srinagar, India',
  'IXL': 'Leh Kushok Bakula Rimpochee Airport, India',
  'JAI': 'Jaipur International Airport, India',
  'UDR': 'Maharana Pratap Airport, Udaipur, India',
  'JDH': 'Jodhpur Airport, India',
  'GOI': 'Goa International Airport, India',
  'VGA': 'Vijayawada Airport, India',
  'VTZ': 'Visakhapatnam Airport, India',
  'TIR': 'Tirupati Airport, India',
  'NAG': 'Dr. Babasaheb Ambedkar International Airport, Nagpur, India',
  'IXR': 'Ranchi Airport, India',
  'GAY': 'Gaya Airport, India',
  'PAT': 'Jay Prakash Narayan International Airport, Patna, India',
  'VNS': 'Lal Bahadur Shastri Airport, Varanasi, India',
  'LKO': 'Chaudhary Charan Singh International Airport, Lucknow, India',
  'AGR': 'Agra Airport, India',
  'IDR': 'Devi Ahilya Bai Holkar Airport, Indore, India',
  'BHO': 'Raja Bhoj Airport, Bhopal, India',
  'RPR': 'Swami Vivekananda Airport, Raipur, India',
  'BBI': 'Biju Patnaik International Airport, Bhubaneswar, India',
  'ATQ': 'Raja Sansi International Airport, Amritsar, India',
  'IXC': 'Chandigarh Airport, India',
  'DED': 'Dehradun Airport, India',
  'IXU': 'Aurangabad Airport, India',
  'CMB': 'Bandaranaike International Airport, Colombo, Sri Lanka',
  'RML': 'Ratmalana Airport, Colombo, Sri Lanka',
  'HRI': 'Mattala Rajapaksa International Airport, Hambantota, Sri Lanka',
  'DAC': 'Hazrat Shahjalal International Airport, Dhaka, Bangladesh',
  'CGP': 'Shah Amanat International Airport, Chittagong, Bangladesh',
  'SPD': 'Saidpur Airport, Bangladesh',
  'JSR': 'Jessore Airport, Bangladesh',
  'CXB': 'Cox\'s Bazar Airport, Bangladesh',

  // MIDDLE EAST & AFRICA
  'DXB': 'Dubai International Airport, UAE',
  'AUH': 'Abu Dhabi International Airport, UAE',
  'SHJ': 'Sharjah International Airport, UAE',
  'RKT': 'Ras Al Khaimah International Airport, UAE',
  'DWC': 'Al Maktoum International Airport, Dubai, UAE',
  'AAN': 'Al Ain International Airport, UAE',
  'JED': 'King Abdulaziz International Airport, Jeddah, Saudi Arabia',
  'RUH': 'King Khalid International Airport, Riyadh, Saudi Arabia',
  'DMM': 'King Fahd International Airport, Dammam, Saudi Arabia',
  'MED': 'Prince Mohammad Bin Abdulaziz Airport, Medina, Saudi Arabia',
  'TIF': 'Taif Regional Airport, Saudi Arabia',
  'DOH': 'Hamad International Airport, Doha, Qatar',
  'MCT': 'Muscat International Airport, Oman',
  'SLL': 'Salalah Airport, Oman',
  'KWI': 'Kuwait International Airport, Kuwait',
  'BAH': 'Bahrain International Airport, Bahrain',
  'AMM': 'Queen Alia International Airport, Amman, Jordan',
  'AQJ': 'King Hussein International Airport, Aqaba, Jordan',
  'BGW': 'Baghdad International Airport, Iraq',
  'BSR': 'Basra International Airport, Iraq',
  'EBL': 'Erbil International Airport, Iraq',
  'BEY': 'Rafic Hariri International Airport, Beirut, Lebanon',
  'DAM': 'Damascus International Airport, Syria',
  'ALP': 'Aleppo International Airport, Syria',
  'TLV': 'Ben Gurion Airport, Tel Aviv, Israel',
  'VDA': 'Ovda Airport, Israel',
  'ETH': 'Eilat Airport, Israel',
  'HFA': 'Haifa Airport, Israel',
  'CAI': 'Cairo International Airport, Egypt',
  'HRG': 'Hurghada International Airport, Egypt',
  'SSH': 'Sharm el-Sheikh International Airport, Egypt',
  'LXR': 'Luxor International Airport, Egypt',
  'ASW': 'Aswan International Airport, Egypt',
  'ALY': 'Alexandria International Airport, Egypt',
  'JNB': 'OR Tambo International Airport, Johannesburg, South Africa',
  'CPT': 'Cape Town International Airport, South Africa',
  'DUR': 'King Shaka International Airport, Durban, South Africa',
  'PLZ': 'Port Elizabeth Airport, South Africa',
  'GRJ': 'George Airport, South Africa',
  'BFN': 'Bram Fischer International Airport, Bloemfontein, South Africa',
  'KIM': 'Kimberley Airport, South Africa',
  'WDH': 'Hosea Kutako International Airport, Windhoek, Namibia',
  'WVB': 'Walvis Bay Airport, Namibia',
  'GOG': 'Sir Seretse Khama International Airport, Gaborone, Botswana',
  'MUB': 'Maun Airport, Botswana',
  'HRE': 'Harare International Airport, Zimbabwe',
  'BUQ': 'Bulawayo Airport, Zimbabwe',
  'VFA': 'Victoria Falls Airport, Zimbabwe',
  'LUN': 'Kenneth Kaunda International Airport, Lusaka, Zambia',
  'LVI': 'Livingstone Airport, Zambia',
  'NLA': 'Ndola Airport, Zambia',
  'MAP': 'Maputo International Airport, Mozambique',
  'BEW': 'Beira Airport, Mozambique',
  'VPY': 'Chimoio Airport, Mozambique',
  'VNX': 'Vilanculos Airport, Mozambique',
  'NBO': 'Jomo Kenyatta International Airport, Nairobi, Kenya',
  'MBA': 'Mombasa Moi International Airport, Kenya',
  'KIS': 'Kisumu Airport, Kenya',
  'EDL': 'Eldoret International Airport, Kenya',
  'MYD': 'Malindi Airport, Kenya',
  'ADD': 'Addis Ababa Bole International Airport, Ethiopia',
  'DIR': 'Aba Tenna Dejazmach Yilma Airport, Dire Dawa, Ethiopia',
  'BJR': 'Bahar Dar Airport, Ethiopia',
  'GDQ': 'Gondar Airport, Ethiopia',
  'MQX': 'Makale Airport, Ethiopia',
  'LLI': 'Lalibela Airport, Ethiopia',
  'NDJ': 'N\'Djamena Airport, Chad',
  'AEH': 'Abéché Airport, Chad',
  'CAS': 'Casablanca Mohammed V International Airport, Morocco',
  'RAK': 'Marrakech Menara Airport, Morocco',
  'AGA': 'Agadir Al Massira Airport, Morocco',
  'FEZ': 'Fès–Saïs Airport, Morocco',
  'TNG': 'Tangier Ibn Battouta Airport, Morocco',
  'RBA': 'Rabat-Salé Airport, Morocco',
  'OUD': 'Oujda Angads Airport, Morocco',
  'ALG': 'Houari Boumediene Airport, Algiers, Algeria',
  'ORN': 'Ahmed Ben Bella Airport, Oran, Algeria',
  'CZL': 'Mohamed Boudiaf International Airport, Constantine, Algeria',
  'AAE': 'Annaba Airport, Algeria',
  'TUN': 'Tunis Carthage International Airport, Tunisia',
  'MIR': 'Monastir Habib Bourguiba International Airport, Tunisia',
  'SFA': 'Sfax Thyna International Airport, Tunisia',
  'DJE': 'Djerba Zarzis International Airport, Tunisia',
  'TOE': 'Tozeur Nefta International Airport, Tunisia',
  'TIP': 'Tripoli International Airport, Libya',
  'BEN': 'Benina International Airport, Benghazi, Libya',
  'SEB': 'Sebha Airport, Libya',

  // OCEANIA
  'SYD': 'Sydney Kingsford Smith Airport, Australia',
  'MEL': 'Melbourne Airport, Australia',
  'BNE': 'Brisbane Airport, Australia',
  'PER': 'Perth Airport, Australia',
  'ADL': 'Adelaide Airport, Australia',
  'CBR': 'Canberra Airport, Australia',
  'HBA': 'Hobart Airport, Australia',
  'DRW': 'Darwin International Airport, Australia',
  'CNS': 'Cairns Airport, Australia',
  'TSV': 'Townsville Airport, Australia',
  'ROK': 'Rockhampton Airport, Australia',
  'MCY': 'Sunshine Coast Airport, Australia',
  'MKY': 'Mackay Airport, Australia',
  'HTI': 'Hamilton Island Airport, Australia',
  'ASP': 'Alice Springs Airport, Australia',
  'AYQ': 'Ayers Rock Airport, Australia',
  'KGI': 'Kalgoorlie Airport, Australia',
  'BRO': 'Broome International Airport, Australia',
  'NLF': 'Norfolk Island Airport, Australia',
  'AKL': 'Auckland Airport, New Zealand',
  'WLG': 'Wellington Airport, New Zealand',
  'CHC': 'Christchurch Airport, New Zealand',
  'ZQN': 'Queenstown Airport, New Zealand',
  'DUD': 'Dunedin Airport, New Zealand',
  'IVC': 'Invercargill Airport, New Zealand',
  'HLZ': 'Hamilton Airport, New Zealand',
  'ROT': 'Rotorua Airport, New Zealand',
  'TRG': 'Tauranga Airport, New Zealand',
  'GIS': 'Gisborne Airport, New Zealand',
  'NPE': 'Hawke\'s Bay Airport, Napier, New Zealand',
  'PMR': 'Palmerston North Airport, New Zealand',
  'NSN': 'Nelson Airport, New Zealand',
  'BHE': 'Woodbourne Airport, Blenheim, New Zealand',
  'TUO': 'Taupo Airport, New Zealand',
  'KKE': 'Kerikeri Airport, New Zealand',
  'WKA': 'Wanaka Airport, New Zealand'
}

/**
 * Convert IATA airport code to full airport name
 * @param iataCode - 3-letter airport code (e.g., "SIN", "YVR")
 * @returns Full airport name or fallback with code
 */
export function getAirportName(iataCode: string): string {
  if (!iataCode) return ''
  
  const upperCode = iataCode.toUpperCase().trim()
  const airportName = AIRPORT_CODES[upperCode]
  
  // If we have the airport name in our lookup table, return it
  // If not, return a formatted fallback
  return airportName || `${upperCode} Airport`
}
